### ISSUE TITLE
incorrect import while using closures in body form {}

### ISSUE THREAD

**Issue by yankeppey** [stanfy/helium#103]
Hi,
thank you for such a great tool. I use the latest gradle-plugin (classpath 'com.stanfy.helium:gradle-plugin:0.6.0-SNAPSHOT')

Unfortunately such service method spec

    post "/users" spec {
        name "register_user"
        parameters {
            apikey 'string'
        }
        body form {
            email 'string'
            password 'string'
        }
    }

generates incorrect import:

"import post_users_body_POST;"

I guess there shouldn't be any import here.

Thanks,
Andrei.

**Comment by roman-mazur** [comment]
Yeah, definitely a bug. We should fix it soon.
Ping @nolia.
