### ISSUE TITLE
The modifier 'sequence' is ignored when the plugin generates API from a specs file.

### ISSUE THREAD

**Issue by Arororo** [stanfy/helium#121]
The modifier 'sequence' is ignored when the plugin generates API from a specs file.

```
get "/aaa/bbb" spec {
    name 'aaabbb'
    description "Returns list of bbb."
    parameters {
      pg       'int32'
      states      'int32' sequence
    }
    response "AaaBbbResponse"
  }
```
The method is generating; however, parameter `states` turning into `... @Query("states") int states ...`; meanwhile, it expected to be `... @Query("states") int[] states ...`.

**Comment by roman-mazur** [comment]
Thanks for the report!
