### ISSUE TITLE
Exceptions in custom readers are not propagated correctly

### ISSUE THREAD

**Issue by Vandalko** [stanfy/helium#171]
So, [ClosureJsonConverter](https://github.com/stanfy/helium/blob/4a76cbf962fbaa79461cb93abcb5511f6418b30f/helium/src/main/groovy/com/stanfy/helium/format/json/ClosureJsonConverter.groovy) exists with two essential methods:

```groovy
  public static final Closure<?> AS_STRING_READER = { JsonReader reader ->
    JsonToken nextToken = reader.peek();
    if (nextToken != JsonToken.STRING) {
      throw new IllegalArgumentException("not a string");
    }
    return reader.nextString()
  }
```

and

```groovy
  @Override
  Object value(JsonReader input, Type type) throws IOException {
    try {
      return reader.call(input)
    } catch (IllegalStateException | IllegalArgumentException e) {
      if (!checkForEnd(input)) {
        input.skipValue();
      }
      throw e;
    }
  }
```

Let's define a custom spec:
```groovy
type "defaultValue" spec {
  description "Form field default value"
  from("json") { asString() }
  to("json") { asString() }
}

type "Values" message {
 value 'defaultValue'
 meta 'string'
}
```

What would happen if we try to parse:

```json
{
"value": ["array"],
"meta": "record"
}
```

One may expect that reader would throw `IllegalArgumentException` which would be caught and invalid value would be simply skipped.
But then [TypeDsl](https://github.com/stanfy/helium/blob/4a76cbf962fbaa79461cb93abcb5511f6418b30f/helium/src/main/groovy/com/stanfy/helium/internal/dsl/TypeDsl.groovy#L80) exists with next code:

```groovy
    formats.each { String format ->
      def reader = proxy.@readers[format], writer = proxy.@writers[format]
      if (reader) {
        dsl.typeResolver.addTypeReader(format, type, { def input, def type ->
          return reader(input)
        } as PrimitiveReader<?>)
      }
      if (writer) {
        dsl.typeResolver.addTypeWriter(format, type, { def output, def type, Object value ->
          return writer(output, value)
        } as PrimitiveWriter<?>)
      }
    }
```

Essentially, it register new `PrimitiveReader` which in our case would call `AS_STRING_READER` reader closure, but exception thrown (`IllegalArgumentException`) would not be processed so invalid value would not be skipped, and as a result, further json processing would fail because instead of reading expected next record in json object, we would still be sitting on failed value. As a result - our test (json parsing) would fail on `Values.meta` field telling us something like: `Json parse exception - expected NAME, but got BEGIN_ARRAY`

**Comment by roman-mazur** [comment]
@Vandalko can it be closed?

**Comment by Vandalko** [comment]
closed by https://github.com/stanfy/helium/pull/172
