### ISSUE TITLE
Generate toString() without newline characters

### ISSUE THREAD

**Issue by nazlo** [stanfy/helium#182]
Whenever `java` entities are generated, corresponding `toString()` method is also generated. The issue is: generated `toString()` uses `\n` characters in it. If a client wants to use generated entities in log statements, then the particular statement is spread across multiple lines. 
This makes impossible logs indexing with `elastic search` or `aws cloud watch`.

I suggest to 
1) Remove `toString()` generation
2) Add annotation `@lombok.Data` on each java entity
3) Add `lombok` as `compileOnly` dependency for `helium-java`

**Comment by roman-mazur** [comment]
please post to https://github.com/Keypr/helium
